version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases: 
  install: 
    runtime-versions: 
      docker: 18 
  pre_build: 
    commands: 
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-9)
      - IMAGE_TAG=${COMMIT_HASH:=latest} 
  build: 
    commands: 
      - echo Build started on `date` 
      - echo Building the Docker image 
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG . 
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG   
  post_build: 
    commands: 
      - echo Build complete on `date` 
      - echo Pushing the Docker image 
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"imageUri":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - imageDetail.json 
cache:
  paths:
    - '/root/.m2/**/*'